name: Build [Weekly]

on:
  workflow_dispatch:
    
  #schedule:
    #- cron: "0 0 * * 0"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    environment: main
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
       path: ./node_modules
       key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts

    - name: Scrapping
      run: npm run start --if-present 
      env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

    - name: Test
      run: npm run test

    - name: Stage, commit and push files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_user_name: "typeselector-bot"
          commit_user_email: "typeselector-bot@users.noreply.github.com"
          commit_author: "typeselector-bot <typeselector-bot@users.noreply.github.com>"
          commit_message: "chore(build): update packages [Weekly]"
      continue-on-error: false
